version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mvc_app
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      SQL_CONNECTION_STRING:  "Server=localhost,5000;Database=ProductsDb;Trusted_Connection=false;MultipleActiveResultSets=true;Encrypt=false;user id=sa;password=Password1;"
    networks:
      - appnet

volumes:
  sql_data:

networks:
  appnet:
